# Configuration for the P2P File Sharing Network

tracker:
  host: "127.0.0.1" # Use 0.0.0.0 to listen on all network interfaces
  port: 9090
  buffer_size: 4096 # 4KB buffer for socket communication

peer:
  chunk_size: 1048576 # 1 MB (1024 * 1024)
